steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloudeval-255302/eval-multi-base-20_04', '-f', 'Dockerfile-20.04', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloudeval-255302/eval-multi-base-20_04']
