name: build and test

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
  
      - name: build docker image
        run: docker build -f Dockerfile-20.04 -t eval-multi-base-20_04:latest .
      
      - name: build docker image for tests
        run: docker build -f Dockerfile-tests -t eval-multi-base-tests:latest .

      - name: run tests
        run: docker run --rm eval-multi-base-tests:latest /home/runner/do/run_tests.sh

